name: Scopy
options:
  bundleIdPrefix: com.scopy
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

schemes:
  Scopy:
    build:
      targets:
        Scopy: all
        ScopyTests: [test]
        ScopyUITests: [test]
    test:
      targets:
        - ScopyTests
        - ScopyUITests

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    INFOPLIST_FILE: Scopy/Info.plist
    CODE_SIGN_ENTITLEMENTS: Scopy/Scopy.entitlements
    PRODUCT_BUNDLE_IDENTIFIER: com.scopy.app
    BUILD_DIR: $(SRCROOT)/.build
    CONFIGURATION_BUILD_DIR: $(BUILD_DIR)/$(CONFIGURATION)
    # 版本号配置 (v0.6)
    MARKETING_VERSION: "0.6.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  Scopy:
    type: application
    platform: macOS
    sources:
      - path: Scopy
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_NAME: Scopy
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: Scopy/Info.plist
    dependencies:
      - sdk: libsqlite3.tbd

  ScopyTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ScopyTests
      # 独立测试 bundle 模式：直接包含应用源码，避免 SwiftUI App 生命周期冲突
      - path: Scopy
        excludes:
          - "**/*.md"
          - "main.swift"       # 排除应用入口，避免 @main 冲突
          - "ScopyApp.swift"   # 排除 SwiftUI App，避免 NSApplication 冲突
          - "Info.plist"
          - "*.entitlements"
    settings:
      base:
        PRODUCT_NAME: ScopyTests
        PRODUCT_BUNDLE_IDENTIFIER: com.scopy.tests
        GENERATE_INFOPLIST_FILE: true
        # 不设置 TEST_HOST 和 BUNDLE_LOADER，使用独立测试 bundle 模式
    dependencies:
      - sdk: libsqlite3.tbd

  ScopyUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: ScopyUITests
    settings:
      base:
        PRODUCT_NAME: ScopyUITests
        PRODUCT_BUNDLE_IDENTIFIER: com.scopy.uitests
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: Scopy
    dependencies:
      - target: Scopy
