name: Scopy
options:
  bundleIdPrefix: com.scopy
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

schemes:
  Scopy:
    build:
      targets:
        Scopy: all
        ScopyTests: [test]
        ScopyUITests: [test]
    test:
      targets:
        - ScopyTests
        - ScopyUITests
  ScopyTSan:
    build:
      targets:
        ScopyTestHost: all
        ScopyTSanTests: [test]
    test:
      targets:
        - ScopyTSanTests

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_ENTITLEMENTS: Scopy/Scopy.entitlements
    PRODUCT_BUNDLE_IDENTIFIER: com.scopy.app
    BUILD_DIR: $(SRCROOT)/.build
    CONFIGURATION_BUILD_DIR: $(BUILD_DIR)/$(CONFIGURATION)
    # SwiftPM packages still build into DerivedData; add search paths so App/Test targets can `import ScopyKit`
    SWIFT_INCLUDE_PATHS: "$(inherited) $(OBJROOT)/../Products/$(CONFIGURATION)"
    FRAMEWORK_SEARCH_PATHS: "$(inherited) $(OBJROOT)/../Products/$(CONFIGURATION)"
    # 版本号配置 (v0.6)
    # Note: 发布版本统一由 git tag 驱动，详见 scripts/version.sh 与 DEPLOYMENT.md。
    MARKETING_VERSION: "0.0.0"
    CURRENT_PROJECT_VERSION: "0"

packages:
  ScopyKit:
    path: .

targets:
  Scopy:
    type: application
    platform: macOS
    sources:
      - path: Scopy
        excludes:
          - "**/*.md"
          # Phase 7 (v0.43): App target only keeps App/UI/Presentation.
          # Backend (Domain/Application/Infrastructure/Services/Utilities) is provided by SwiftPM module `ScopyKit`.
          - "Application/**"
          - "Domain/**"
          - "Extensions/**"
          - "Infrastructure/**"
          - "Models/**"
          - "Protocols/**"
          - "Services/**"
          - "Utilities/**"
    settings:
      base:
        PRODUCT_NAME: Scopy
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: Scopy/Info.plist
    dependencies:
      - sdk: libsqlite3.tbd
      - package: ScopyKit
        product: ScopyKit

  ScopyTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ScopyTests
      # 独立测试 bundle 模式：直接包含应用源码，避免 SwiftUI App 生命周期冲突
      - path: Scopy
        excludes:
          - "**/*.md"
          - "main.swift"       # 排除应用入口，避免 @main 冲突
          - "ScopyApp.swift"   # 排除 SwiftUI App，避免 NSApplication 冲突
          - "Info.plist"
          - "*.entitlements"
          # Phase 7 (v0.43): Do not compile backend sources into tests; use `ScopyKit` dependency instead.
          - "Application/**"
          - "Domain/**"
          - "Extensions/**"
          - "Infrastructure/**"
          - "Models/**"
          - "Protocols/**"
          - "Services/**"
          - "Utilities/**"
    settings:
      base:
        PRODUCT_NAME: ScopyTests
        PRODUCT_BUNDLE_IDENTIFIER: com.scopy.tests
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_NSPrincipalClass: XCTestCase
        # 不设置 TEST_HOST 和 BUNDLE_LOADER，使用独立测试 bundle 模式
    dependencies:
      - sdk: libsqlite3.tbd
      - package: ScopyKit
        product: ScopyKit

  ScopyTestHost:
    type: application
    platform: macOS
    sources:
      - path: ScopyTestHost
    settings:
      base:
        PRODUCT_NAME: ScopyTestHost
        PRODUCT_BUNDLE_IDENTIFIER: com.scopy.testhost
        GENERATE_INFOPLIST_FILE: true

  ScopyTSanTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ScopyTests
        excludes:
          - "IntegrationTests.swift"
          - "PerformanceTests.swift"
      # Hosted test bundle mode: includes app sources but excludes entrypoints to avoid @main conflicts.
      - path: Scopy
        excludes:
          - "**/*.md"
          - "main.swift"
          - "ScopyApp.swift"
          - "Info.plist"
          - "*.entitlements"
          # Phase 7 (v0.43): Do not compile backend sources into tests; use `ScopyKit` dependency instead.
          - "Application/**"
          - "Domain/**"
          - "Extensions/**"
          - "Infrastructure/**"
          - "Models/**"
          - "Protocols/**"
          - "Services/**"
          - "Utilities/**"
    settings:
      base:
        PRODUCT_NAME: ScopyTSanTests
        PRODUCT_BUNDLE_IDENTIFIER: com.scopy.tsan.tests
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_NSPrincipalClass: XCTestCase
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ScopyTestHost.app/Contents/MacOS/ScopyTestHost"
        BUNDLE_LOADER: "$(TEST_HOST)"
        OTHER_SWIFT_FLAGS: "$(inherited) -DSCOPY_TSAN_TESTS"
    dependencies:
      - target: ScopyTestHost
      - sdk: libsqlite3.tbd
      - package: ScopyKit
        product: ScopyKit

  ScopyUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: ScopyUITests
    settings:
      base:
        PRODUCT_NAME: ScopyUITests
        PRODUCT_BUNDLE_IDENTIFIER: com.scopy.uitests
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: Scopy
    dependencies:
      - target: Scopy
